# Generated by Django 4.0.5 on 2022-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('card_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
